palette = "catppuccin_mocha"
format = """
$hostname\
$directory\
$python\
$git_state\
$sudo\

$fill\

$git_branch\
$git_status\
$git_commit\
$cmd_duration\

$line_break\

$character"""

[python]
format = '[$symbol \($virtualenv\)]($style)'
symbol = ""

[character]
success_symbol = "[ ❯](sky)"
error_symbol = "[ ❯](red)"

[fill]
symbol = ' '

[hostname]
ssh_only = true
format = "[](fg: bg:none)[█](fg:rosewater bg:base)[$ssh_symbol$hostname](bold bg:rosewater)[](fg:rosewater bg:none) "
disabled = false

[directory]
format = "[](fg:base bg:none)[$path]($style)[█](fg:base bg:base)[](fg:blue bg:base)[](fg:base bg:blue)[ ](fg:sapphire bg:none)"
style = "fg:text bg:base bold"
truncation_length = 3
truncate_to_repo = false
read_only = " "

[cmd_duration]
min_time = 1
show_milliseconds = true
format = "[](fg:base bg:none)[$duration]($style)[](fg:base bg:base)[](fg:mauve bg:base)[󱑂](fg:base bg:mauve)[](fg:mauve bg:none)"
disabled = false
style = "fg:text bg:base bold"

[git_branch]
format = "[](fg:base bg:none)[$branch]($style)[](fg:base bg:base)[](fg:green bg:base)[](fg:base bg:green)[](fg:green bg:none) "
style = "fg:text bg:base bold"
symbol = ""

[git_status]
format = "[](fg:base bg:none)[$all_status$ahead_behind]($style)[](fg:base bg:base)[](fg:blue bg:base)[](fg:base bg:blue)[](fg:blue bg:none) "
style = "fg:text bg:base"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = " 󰄸 "
untracked = "[ +${count}](fg:green bg:base)"
stashed = "&"
modified = "[ ~${count}](fg:yellow bg:base)"
staged = "+"
renamed = "[ »${count}](fg:peach bg:base)"
deleted = "[ -${count}](fg:red bg:base)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
